### ISSUE TITLE
Feature Request: Should have 'key' WITH VALUE 'value'

### ISSUE THREAD

**Issue by KSoto** [hidroh/cucumber-api#1]
Feature Request.

Can we add functionality to do something like this?:

`Then the response should have key “firstName” with value “Katie”`

Right now we have this:

`Then the response should have key “firstName”`

**Comment by hidroh** [comment]
Yeah that's doable, probably something along the line `Then the response should have key "key" with type "type" and value "value"`, as we need the type in order to cast the value and assert it.

I'll add it when I have free time, haven't been doing Ruby for a while. You're welcome to make a PR as well!
